services:
    grafana:
        image: grafana/grafana-oss
        ports: 
            - "3000:3000"
        volumes:
            - grafana:/var/lib/grafana
    influxdb:
        image: influxdb:2.2-alpine
        volumes:
            - influxdb:/var/lib/influxdb2
        ports:
            - "8086:8086"
        environment:
            - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=initadmintoken
            - DOCKER_INFLUXDB_INIT_BUCKET=sensor
            - DOCKER_INFLUXDB_INIT_MODE=setup
            - DOCKER_INFLUXDB_INIT_ORG=admin
            - DOCKER_INFLUXDB_INIT_PASSWORD=initpassword
            - DOCKER_INFLUXDB_INIT_RETENTION=1w # One Week
            - DOCKER_INFLUXDB_INIT_USERNAME=initusername

volumes:
  influxdb:
  grafana: